### ISSUE TITLE
When changing a ConfigItem, it's changed value is not updated in the class, though it's changed in the camera settings

### ISSUE THREAD

**Issue by define-private-public** [jbaiter/gphoto2-cffi#20]
Say that I got the `ISO Speed` from my camera's config and then modified the ISO field, it will change the ISO in the camera, but if I do a `print(iso_setting)` it will show the original value.

I think it's because `self.value` isn't being set in this function:
https://github.com/jbaiter/gphoto2-cffi/blob/master/gphoto2cffi/gphoto2.py#L463

I can provide some source code to display the issue if needed, but I don't think it's required.

**Comment by thijstriemstra** [comment]
Can you put out a new release?
