### ISSUE TITLE
Include gphoto2.cdef in distribution

### ISSUE THREAD

**Issue by thijstriemstra** [jbaiter/gphoto2-cffi#4]
It seems https://github.com/jbaiter/gphoto2-cffi/blob/master/gphoto2/gphoto2.cdef isn't installed causing a traceback (that I can't reproduce now) when you first use the library. Copying the file manually to site-packages fixed the problem.

**Comment by thijstriemstra** [comment]
Adding it to a MANIFEST file would solve this.

**Comment by jbaiter** [comment]
Sorry it took almost 6  months, it's now fixed via an explicit `package_data` dictionary, but thanks for the suggestion with the `MANIFEST`. I think those files are not needed with newer setuptools versions any more.
